name: Assign copilot

on:
  issues:
    types: [opened, reopened]

jobs:
  assign-copilot:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Assign issue to Copilot
        run: |
            gh issue edit ${{ github.event.issue.number }} --add-assignee "@copilot" --repo ${{ github.repository }}
        env:
            GH_TOKEN: ${{ github.token }}